swagger: '2.0'
info:
  version: '1.0'
  title: "API 6.0"
  description: Polls is a simple API allowing consumers to view polls and vote in them.
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: polls.apiblueprint.org
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /promotions/{PromotionCode}:
    x-summary: Promotions
    get:
      summary: Get a promotion
      parameters:
        - in: path
          name: PromotionCode
          description: Promotion unique identifier
          required: true
          type: string
      responses:
        200:
          description: Get a promotion
          schema:
              $ref: '#/definitions/Promotion'
          examples:
            application/json:
              Code: 3EC33F22ED
              Name: 100%
              Description: ''
              StartDate: 
              EndDate: 
              MaximumOrdersNumber: -1
              MaximumQuantity: -1
              InstantDiscount: false
              Coupon:
                Type: SINGLE
                Code: 100procent
              Enabled: true
              ChannelType: ECOMMERCE
              Type: RENEWAL
              Discount:
                Type: PERCENT
                Value: '100'
              Products:
              - Code: priceTEST0
                PricingOptionCodes: []
                PricingConfigurationCode: 54BCE2AB95
              PriceThreshold:
                Amount: 
                Currency: 
              Translations:
              - Name: 100%
                Language: EN
              - Name: 100%
                Language: FR
              Sources: []
              PublishToAffiliatesNetwork: 0
              ApplyRecurring: NONE
              RecurringChargesNumber: '0'
  /promotions:
    x-summary: Promotions
    post:
      summary: Create a promotion
      parameters:
        - in: body
          name: Create a promotion
          description: Promotion details
          required: true
          schema: 
            $ref: '#/definitions/Promotion'
      responses:
        200:
          description: Get a promotion
          schema:
              $ref: '#/definitions/Promotion'
          examples:
            application/json:
              Code: 3EC33F22ED
              Name: 100%
              Description: ''
              StartDate: 
              EndDate: 
              MaximumOrdersNumber: -1
              MaximumQuantity: -1
              InstantDiscount: false
              Coupon:
                Type: SINGLE
                Code: 100procent
              Enabled: true
              ChannelType: ECOMMERCE
              Type: RENEWAL
              Discount:
                Type: PERCENT
                Value: '100'
              Products:
              - Code: priceTEST0
                PricingOptionCodes: []
                PricingConfigurationCode: 54BCE2AB95
              PriceThreshold:
                Amount: 
                Currency: 
              Translations:
              - Name: 100%
                Language: EN
              - Name: 100%
                Language: FR
              Sources: []
              PublishToAffiliatesNetwork: 0
              ApplyRecurring: NONE
              RecurringChargesNumber: '0'
          
definitions:
  Promotion:
    title: Promotion
    type: object
    properties:
      Code:
        type: string
      Name:
        type: string
      Description:
        type: string
      StartDate:
        type: string
        format: date
      EndDate:
        type: string
        format: date
      MaximumOrdersNumber:
        type: integer
      MaximumQuantity:
        type: integer
      InstantDiscount:
        type: boolean
      Coupon:
        type: object
        properties: 
          Type: 
            type: string
          Code:
            type: string
      Enabled: 
        type: boolean
      ChannelType:
        type: string
      Type: 
        type: string
      Discount:
        type: object
        properties:
          Type: 
            type: string
          Value:
            type: number
            format: double
      Products:
        type: array
        items:
          $ref: '#/definitions/PromotionProduct'
      PriceThreshold:
        type: object
        properties:
          Amount: 
            type: number
            format: double
          Currency:
            type: string
      Translations:
        type: array
        items:
          $ref: '#/definitions/PromotionProductTranslation'
      Sources:
        type: array
        items:
          type: string
      PublishToAffiliatesNetwork:
        type: integer
      ApplyRecurring:
        type: string
      RecurringChargesNumber:
        type: integer
      
  PromotionProduct:
    title: Promotion Product
    type: object
    properties:
      Code: 
        type: string
      PricingOptionCodes:
        type: array
        items:
          type: string
      PricingConfigurationCode:
        type: string
  PromotionProductTranslation:
    title: Promotion Product Translation
    type: object
    properties:
      Name: 
        type: string
      Language:
        type: string